apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-server.fullname" . }}
  labels:
    {{- include "app-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-server.fullname" . }}-lb
  labels: {{- include "app-server.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/load-balancer-type: "internal"
spec:
  type: LoadBalancer
  # see. terraform -> dns.tf
  loadBalancerIP: "10.146.0.18"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "app-server.selectorLabels" . | nindent 4 }}
